In [1]:
import numpy as np
import pandas as pd

In [9]:
# Define the file path
file_path = r"C:\Users\mail2\OneDrive\Desktop\MY_DRIVE\MLOps\MLOps-Addy\sample_data.csv"

# Read the CSV file
df = pd.read_csv(file_path)

# Print the contents of the file
print(df)

   Unnamed: 0   Name  Age         City  Salary
0           0  Vijay   25     New York   50000
1           1  Benyl   35  Los Angeles   60000
2           2    Sam   32      Chicago   70000
3           3    Ram   40      Houston   80000
4           4   Kian   45      Phoenix   55000

In [10]:
pd.DataFrame(df)

   Unnamed: 0   Name  Age         City  Salary
0           0  Vijay   25     New York   50000
1           1  Benyl   35  Los Angeles   60000
2           2    Sam   32      Chicago   70000
3           3    Ram   40      Houston   80000
4           4   Kian   45      Phoenix   55000

In [12]:
tail=df.tail(2)
print(tail)

   Unnamed: 0  Name  Age     City  Salary
3           3   Ram   40  Houston   80000
4           4  Kian   45  Phoenix   55000

In [17]:
df.query('Age > 30')

   Unnamed: 0   Name  Age         City  Salary
1           1  Benyl   35  Los Angeles   60000
2           2    Sam   32      Chicago   70000
3           3    Ram   40      Houston   80000
4           4   Kian   45      Phoenix   55000