In [1]:
import numpy as np
import pandas as pd

In [2]:
# Define the file path
file_path = r"C:\Users\mail2\OneDrive\Desktop\MY_DRIVE\MLOps\MLOps-Addy\sample_data.csv"

# Read the CSV file
data = pd.read_csv(file_path)

# Print the contents of the file
#print(df)
data.head(7)

   Unnamed: 0   Name  Age         City  Salary
0           0  Vijay   25     New York   50000
1           1  Benyl   35  Los Angeles   60000
2           2    Sam   32      Chicago   70000
3           3    Ram   40      Houston   80000
4           4   Kian   45      Phoenix   55000

In [3]:
pd.DataFrame(data)

   Unnamed: 0   Name  Age         City  Salary
0           0  Vijay   25     New York   50000
1           1  Benyl   35  Los Angeles   60000
2           2    Sam   32      Chicago   70000
3           3    Ram   40      Houston   80000
4           4   Kian   45      Phoenix   55000

In [4]:
tail=data.tail(2)
print(tail)

   Unnamed: 0  Name  Age     City  Salary
3           3   Ram   40  Houston   80000
4           4  Kian   45  Phoenix   55000

In [5]:
data.query('Age > 30')

   Unnamed: 0   Name  Age         City  Salary
1           1  Benyl   35  Los Angeles   60000
2           2    Sam   32      Chicago   70000
3           3    Ram   40      Houston   80000
4           4   Kian   45      Phoenix   55000

In [6]:
data.tail(2)

   Unnamed: 0  Name  Age     City  Salary
3           3   Ram   40  Houston   80000
4           4  Kian   45  Phoenix   55000

In [7]:
data.describe()

       Unnamed: 0        Age        Salary
count    5.000000   5.000000      5.000000
mean     2.000000  35.400000  63000.000000
std      1.581139   7.635444  12041.594579
min      0.000000  25.000000  50000.000000
25%      1.000000  32.000000  55000.000000
50%      2.000000  35.000000  60000.000000
75%      3.000000  40.000000  70000.000000
max      4.000000  45.000000  80000.000000

In [8]:
data.isna().sum()

Unnamed: 0    0
Name          0
Age           0
City          0
Salary        0
dtype: int64

In [12]:
data[data["Age"]=40]

SyntaxError: cannot assign to subscript here. Maybe you meant '==' instead of '='? (204764327.py, line 1)

In [20]:
data[data["City"]=="New York"]

   Unnamed: 0   Name  Age      City  Salary
0           0  Vijay   40  New York   50000

In [21]:
data[data["City"]>="New York"]

   Unnamed: 0   Name  Age      City  Salary
0           0  Vijay   40  New York   50000
4           4   Kian   40   Phoenix   55000

In [22]:
data[data["Salary"]>=60000]

   Unnamed: 0   Name  Age         City  Salary
1           1  Benyl   40  Los Angeles   60000
2           2    Sam   40      Chicago   70000
3           3    Ram   40      Houston   80000

In [23]:
data.groupby('City')['Salary'].mean()

City
Chicago        70000.0
Houston        80000.0
Los Angeles    60000.0
New York       50000.0
Phoenix        55000.0
Name: Salary, dtype: float64

In [24]:
data['Salary'].mean()

np.float64(63000.0)

In [ ]:
data.to_json(r"C:\Users\mail2\OneDrive\Desktop\MY_DRIVE\MLOps\MLOps-Addy\sample_data_output.json", orient='records', lines=True)

In [33]:
df=pd.DataFrame(data)
print(df)
print(df.corr())

   Unnamed: 0   Name  Age         City  Salary
0           0  Vijay   25     New York   50000
1           1  Benyl   35  Los Angeles   60000
2           2    Sam   32      Chicago   70000
3           3    Ram   40      Houston   80000
4           4   Kian   45      Phoenix   55000

ValueError: could not convert string to float: 'Vijay'